import Ably from 'ably';
import { SignalingMessage } from '../types';

export class PulsarSignaling {
  private realtime: Ably.Realtime | null = null;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  private channel: any = null; // Ably channel or BroadcastChannel
  private roomId: string | null = null;
  private peerId: string;
  private messageHandler: ((msg: SignalingMessage) => void) | null = null;
  private mode: 'ably' | 'broadcast' = 'ably';

  constructor(peerId: string) {
    this.peerId = peerId;
  }

  /**
   * Connect to the signaling layer. Determines the transport mode (Ably vs BroadcastChannel fallback).
   */
  async connect(): Promise<void> {
    const ablyKey = process.env.NEXT_PUBLIC_ABLY_KEY;

    // Check if we should use Ably directly via client-side key
    if (ablyKey && ablyKey !== 'your_ably_key_here') {
      try {
        this.realtime = new Ably.Realtime({ key: ablyKey });
        this.mode = 'ably';
        return;
      } catch (err) {
        console.warn('[Signaling] Failed to init Ably with client-side key, trying token auth:', err);
      }
    }

    // Try token auth via Next.js backend API
    try {
      const response = await fetch('/api/signal/token');
      if (!response.ok) {
        throw new Error(`Token endpoint returned status ${response.status}`);
      }
      
      this.realtime = new Ably.Realtime({
        authUrl: '/api/signal/token',
      });
      this.mode = 'ably';
      
      // Wait for connection to verify it works
      await new Promise<void>((resolve, reject) => {
        if (!this.realtime) return reject(new Error('Ably not initialized'));
        
        const onConnected = () => {
          this.realtime?.connection.off('connected', onConnected);
          resolve();
        };
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const onFailed = (err: any) => {
          this.realtime?.connection.off('failed', onFailed);
          reject(new Error(err?.reason?.message || 'Ably connection failed'));
        };
        
        this.realtime.connection.on('connected', onConnected);
        this.realtime.connection.on('failed', onFailed);
        
        // Timeout after 4 seconds to fallback to BroadcastChannel if offline or Ably fails
        setTimeout(() => {
          this.realtime?.connection.off('connected', onConnected);
          reject(new Error('Connection timeout'));
        }, 4000);
      });
    } catch (err) {
      console.warn('[Signaling] Ably token auth unavailable, falling back to BroadcastChannel:', err);
      this.mode = 'broadcast';
    }
  }

  /**
   * Creates a room.
   */
  async createRoom(): Promise<{ roomId: string }> {
    if (this.mode === 'ably') {
      try {
        const response = await fetch('/api/signal/create', { method: 'POST' });
        if (!response.ok) throw new Error('Create room API failed');
        const data = await response.json();
        const roomId = data.roomId;
        await this.joinRoom(roomId);
        return { roomId };
      } catch (err) {
        console.error('[Signaling] Failed to create room via server API:', err);
      }
    }

    // BroadcastChannel or failed API fallback
    const chars = '23456789ABCDEFGHJKLMNPQRSTUVWXYZ';
    let code = '';
    for (let i = 0; i < 6; i++) {
      code += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    await this.joinRoom(code);
    return { roomId: code };
  }

  /**
   * Joins a room.
   */
  async joinRoom(roomId: string): Promise<void> {
    this.roomId = roomId;

    if (this.mode === 'ably' && this.realtime) {
      this.channel = this.realtime.channels.get(`pulsar-room-${roomId}`);
      
      // Subscribe to signals on the Ably channel
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      this.channel.subscribe('signal', (message: any) => {
        const data = message.data as SignalingMessage;
        
        // Filter out signals generated by ourselves
        if ('fromPeer' in data && data.fromPeer === this.peerId) {
          return;
        }
        if (data.type === 'peer-joined' && data.peerId === this.peerId) {
          return;
        }
        
        if (this.messageHandler) {
          this.messageHandler(data);
        }
      });
    } else {
      // BroadcastChannel fallback mode
      console.log(`[Signaling] Operating in BroadcastChannel mode for room: ${roomId}`);
      this.channel = new BroadcastChannel(`pulsar-signal-${roomId}`);
      this.channel.onmessage = (event: MessageEvent) => {
        const data = event.data as SignalingMessage;
        
        // Filter out signals generated by ourselves
        if ('fromPeer' in data && data.fromPeer === this.peerId) {
          return;
        }
        if (data.type === 'peer-joined' && data.peerId === this.peerId) {
          return;
        }
        
        if (this.messageHandler) {
          this.messageHandler(data);
        }
      };
    }
  }

  /**
   * Broadcast message to signaling channel.
   */
  send(msg: SignalingMessage): void {
    if (!this.channel) {
      console.warn('[Signaling] Channel not connected, skipping send');
      return;
    }

    if (this.mode === 'ably') {
      this.channel.publish('signal', msg);
    } else {
      this.channel.postMessage(msg);
    }
  }

  /**
   * Registers callback for incoming signaling messages.
   */
  onMessage(handler: (msg: SignalingMessage) => void): void {
    this.messageHandler = handler;
  }

  /**
   * Disconnect and clean up resources.
   */
  disconnect(): void {
    if (this.channel) {
      try {
        // Send final left signal
        this.send({
          type: 'peer-left',
          peerId: this.peerId,
        } as SignalingMessage);
      } catch {
        // Ignore exit broadcast errors
      }

      if (this.mode === 'ably') {
        this.channel.unsubscribe();
      } else {
        this.channel.close();
      }
    }

    if (this.realtime) {
      this.realtime.close();
    }

    this.realtime = null;
    this.channel = null;
    this.messageHandler = null;
  }
}
